# Generated by Django 3.2.4 on 2021-06-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chronicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_timestamp', models.DateTimeField()),
                ('max_timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('Open', 'open'), ('Closed', 'closed')], default='open', max_length=15)),
                ('unique_id', models.CharField(max_length=50)),
                ('aircraft', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'chronicle',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True)),
                ('aircraft', models.CharField(max_length=50)),
                ('unique_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
