entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

api:
  dashboard: true
  insecure: true

accessLog: {}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    swarmMode: false
    exposedByDefault: false
    watch: true
